image: yazilimvip/hugo-maven:hugo0.72-maven3.6.3

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

stages:
  - build
  - deploy

build:
  stage: build
  before_script:
    - VERSION=$(mvn -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive org.codehaus.mojo:exec-maven-plugin:1.6.0:exec)
  script:
    - mvn $MAVEN_CLI_OPTS compile
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ $CI_DEFAULT_BRANCH
    - if: $VERSION == "/^SNAPSHOT^/"

publish_jar:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS deploy
  rules:
    - if: $CI_COMMIT_TAG