image: yazilimvip/hugo-maven:hugo0.72-maven3.6.3

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

before_script:
  - VERSION=$(mvn -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive org.codehaus.mojo:exec-maven-plugin:1.6.0:exec)
  - export $VERSION

cache:
  paths:
    - .m2/repository/
    - target/

stages:
  - build
  - deploy

compile_mvn:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_MERGE_REQUEST_IID

deploy_jar:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS deploy
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_MERGE_REQUEST_IID && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH && $VERSION == /^SNAPSHOT/

pages:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS javadoc:javadoc
    - mkdir -p public/apidocs && cp -R target/site/apidocs/* public/apidocs
    - cd docs && hugo
    - cd ../ && cp -R docs/public/* public
  artifacts:
    paths:
      - public
  only:
    - tags
