image: maven:3.6.3-jdk-8

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile
  only:
    - master

pages:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS javadoc:javadoc
    - mv target/site/apidocs public
  artifacts:
    paths:
      - public
  only:
    - master




deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS deploy
  only:
    - tags
