image: yazilimvip/hugo-maven:hugo0.72-maven3.6.3

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

stages:
  - build
  - documentation
  - deployment

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile
  only:
    - merge_requests

pages:
  stage: documentation
  script:
    - mvn $MAVEN_CLI_OPTS javadoc:javadoc
    - mkdir -p public/apidocs && cp -R target/site/apidocs/* public/apidocs
    - cd docs && hugo
    - cd ../ && cp -R docs/public/* public
  artifacts:
    paths:
      - public
  only:
    - merge_requests


deploy:
  stage: deployment
  script:
    - mvn $MAVEN_CLI_OPTS deploy
  only:
    - tags