image: maven:3.6.3-jdk-8

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile
  only:
    - master





deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS deploy
  only:
    - tags


pages:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS javadoc:javadoc
    - VERSION=$(mvn -q  -Dexec.executable="echo"  -Dexec.args='${project.version}'  --non-recursive  org.codehaus.mojo:exec-maven-plugin:1.6.0:exec)
    - mv target/site/apidocs public/$VERSION
  artifacts:
    paths:
      - public
  only:
    - master

