name: Build and Publish
on:
  push:
    branches:
      - "main"
jobs:
  mnv_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Configuring Key
        run: |
          echo "${{secrets.GPG_KEY}}" >> private-key.txt
          gpg --import --batch private-key.txt
      - name: Deploying to OSS
        run: mvn clean deploy --batch-mode --settings .m2/settings.xml
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GPG_KEYNAME: ${{secrets.GPG_KEYNAME}}
          GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
          NEXUS_USERNAME: ${{secrets.NEXUS_USERNAME}}
          NEXUS_PASSWORD: ${{secrets.NEXUS_PASSWORD}}